# Generated by Django 2.2.7 on 2019-11-23 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('actionId', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('type', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Actions',
                'db_table': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('actions', models.ForeignKey(db_column='actions', on_delete=django.db.models.deletion.CASCADE, to='backendTest.Actions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propertiesId', models.AutoField(primary_key=True, serialize=False)),
                ('pageFrom', models.TextField(null=True)),
                ('pageTo', models.TextField(null=True)),
                ('viewedId', models.TextField(null=True)),
                ('locationX', models.IntegerField(null=True)),
                ('locationY', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Properties',
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendTest.Profile')),
            ],
            options={
                'verbose_name': 'Session',
                'db_table': 'Session',
            },
        ),
        migrations.AddField(
            model_name='actions',
            name='properties',
            field=models.ForeignKey(db_column='properties', on_delete=django.db.models.deletion.CASCADE, to='backendTest.Properties'),
        ),
    ]
