# Generated by Django 2.2.7 on 2019-11-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actions',
            field=models.ForeignKey(db_column='actions', null=True, on_delete=django.db.models.deletion.CASCADE, to='backendTest.Actions'),
        ),
    ]
