# Generated by Django 2.2.7 on 2019-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
