# Generated by Django 2.2.7 on 2019-11-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0002_auto_20191122_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='actions',
        ),
        migrations.AddField(
            model_name='actions',
            name='profile',
            field=models.ForeignKey(db_column='profile', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendTest.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='actions',
            field=models.ForeignKey(db_column='actions', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendTest.Actions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actions',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
