# Generated by Django 2.2.7 on 2019-11-23 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backendTest', '0005_auto_20191122_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='session',
            name='profile',
        ),
        migrations.AddField(
            model_name='actions',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
