# Generated by Django 2.2.7 on 2019-11-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0006_auto_20191122_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='actions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendTest.Actions'),
        ),
    ]
