# Generated by Django 2.2.7 on 2019-11-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0007_auto_20191122_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='actions',
        ),
        migrations.AddField(
            model_name='properties',
            name='actionId',
            field=models.OneToOneField(db_column='actionId', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendTest.Actions'),
            preserve_default=False,
        ),
    ]
