# Generated by Django 2.2.7 on 2019-11-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0010_auto_20191122_2133'),
    ]

    operations = [
    migrations.AlterField(
        model_name='session',
        name='sessionId',
        field=models.TextField(null=True),
    ),
        migrations.AddField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
