# Generated by Django 2.2.7 on 2019-11-23 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backendTest', '0011_auto_20191122_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='userId',
            field=models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
